name: CI

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  FLUTTER_VERSION: "3.27.0"

jobs:
  build:
    name: Create Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17.x"
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Build runner
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Build apk
        run: flutter build apk --debug

  test:
    name: Run flutter test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17.x"
          cache: gradle
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'
          cache: true
      - name: Get dependencies
        run: flutter pub get
      - name: Build runner
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Run all tests
        run: flutter test
